ba_2motifs:
  groundtruth: "True"
  task_target: "graph"
  task: "binary_classification"
  num_layers: 3
  hidden_dim: 20
  num_epochs: 300
  lr: 0.001
  weight_decay: 0.0000
  dropout: 0.0
  readout: "max"
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  batch_size: 200
  unseen: "False"


powergraph: &powergraph
  groundtruth: "True"
  num_layers: 3
  hidden_dim: 16
  num_epochs: 50
  lr: 0.001
  weight_decay: 0.00005
  dropout: 0.1
  readout: "max"
  train_ratio: 0.85
  val_ratio: 0.05
  test_ratio: 0.1
  batch_size: 8
  unseen: "False"



uk:
  <<: *powergraph

ieee24:
  <<: *powergraph

ieee39:
  <<: *powergraph

ieee118:
  <<: *powergraph
